### ISSUE TITLE
催更催更

### ISSUE THREAD

**Issue by dancingline** [laceyliao/laceyliao.github.io#1]

**Comment by laceyliao** [comment]
???

**Comment by dancingline** [comment]
> ???
本来想围观一下dalao的博客，结果发现并没有文章

**Comment by laceyliao** [comment]
你才是大佬，大佬带带我

**Comment by dancingline** [comment]
> 你才是大佬，大佬带带我

dalao您都已经在搞zero-shot这种热门的东西了
话说在issue里聊天是所有人都能看见的

**Comment by laceyliao** [comment]
看就看咯，反正也不是什么见不得人的东西。。。哎。。。一言难尽

**Comment by dancingline** [comment]
> 看就看咯，反正也不是什么见不得人的东西。。。哎。。。一言难尽

怎么就一言难尽了
